FROM python:3.10-slim
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get install -y ffmpeg \
    && pip install --upgrade pip \
    install -r camera_stream/requirements.txt
CMD ["python", "-m", "camera_stream.main"]